version: '3.8'

services:
  web:
    image: djangostuff
    build:
      context: .
      dockerfile: ./Dockerfile
    command: gunicorn --reload --bind 0.0.0.0:8000 django_stuff.wsgi
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:14.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db

volumes:
  postgres_data:
